
-- Vista 1
CREATE OR REPLACE VIEW MEDIOS_PAGO_CLIENTES AS
SELECT USERS.USER_ID, USERS.NAME || ' ' || USERS.lAST_NAME "Name",
        USERS_PAYMENT.USER_PAYMENT_ID, PAYMENT.TYPE,USERS_PAYMENT.IS_BUSINESS,
        USERS_PAYMENT.NAME_BUSINESS
        FROM USERS INNER JOIN USERS_PAYMENT ON USERS.USER_ID = USERS_PAYMENT.USER_ID
        INNER JOIN PAYMENT ON USERS_PAYMENT.PAYMENT_ID = PAYMENT.PAYMENT_ID;